---
kind: pipeline
name: default

environment:
  TESTE: ola
  TESTE1: mundo
steps:
- name: backend
  image: golang:1.13-alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - go build
  - go test
  - echo $USERNAME
  - echo $USERNAME > a.txt
  - cat a.txt
  - echo $TESTE $TESTE1
